import random
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def random_fill_question(question_div):
    """
    Isi satu pertanyaan random berdasarkan tipe input yang ada:
    - Radio buttons (pilihan tunggal)
    - Checkboxes (pilihan ganda)
    - Text input (isi random kata)
    """
    # Scroll ke question
    driver.execute_script("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", question_div)
    time.sleep(1)

    # Cek radio buttons
    radios = question_div.find_elements(By.XPATH, ".//div[@role='radio']")
    if radios:
        choice = random.choice(radios)
        choice.click()
        time.sleep(0.7)
        return

    # Cek checkboxes
    checkboxes = question_div.find_elements(By.XPATH, ".//div[@role='checkbox']")
    if checkboxes:
        # Pilih random berapa checkbox (minimal 1)
        n = random.randint(1, len(checkboxes))
        chosen = random.sample(checkboxes, n)
        for box in chosen:
            box.click()
            time.sleep(0.4)
        return

    # Cek text input
    inputs = question_div.find_elements(By.TAG_NAME, "input")
    if inputs:
        for input_elem in inputs:
            input_type = input_elem.get_attribute("type")
            if input_type in ['text', 'email', 'number']:
                # Isi random text sederhana
                sample_text = random.choice(["Test", "Random Answer", "Lorem Ipsum", "12345", "Hello"])
                input_elem.send_keys(sample_text)
                time.sleep(0.5)
        return

    # Cek textarea (jawaban paragraf)
    textareas = question_div.find_elements(By.TAG_NAME, "textarea")
    if textareas:
        for ta in textareas:
            ta.send_keys("This is a random answer generated by bot.")
            time.sleep(0.5)
        return

    # Kalau gak ketemu tipe di atas, skip saja
    print("Warning: Tipe pertanyaan tidak dikenali, dilewati.")


def click_button(button_texts):
    """
    Klik tombol sesuai dengan list teks (Next, Berikutnya, Submit, Kirim).
    Kembalikan True jika tombol diklik, False jika tidak ketemu.
    """
    for text in button_texts:
        try:
            btn_xpath = f"//span[contains(text(), '{text}')]/parent::button"
            btn = WebDriverWait(driver, 5).until(
                EC.element_to_be_clickable((By.XPATH, btn_xpath))
            )
            driver.execute_script("arguments[0].scrollIntoView();", btn)
            btn.click()
            time.sleep(3)  # Tunggu halaman load/transition
            return True
        except:
            pass
    return False


def fill_all_sections():
    """
    Isi semua pertanyaan di semua section (halaman) form Google Form sampai submit.
    """
    while True:
        # Cari semua question divs di halaman sekarang
        questions = driver.find_elements(By.XPATH, "//div[@role='listitem']")
        print(f"Ditemukan {len(questions)} pertanyaan di halaman ini.")

        for q in questions:
            random_fill_question(q)

        # Coba klik tombol Next / Berikutnya
        if click_button(['Next', 'Berikutnya']):
            print("Klik tombol Next, lanjut ke section berikutnya...")
            continue  # ulangi loop isi halaman baru

        # Kalau tombol Next gak ada, coba tombol Submit / Kirim
        if click_button(['Submit', 'Kirim']):
            print("Form sudah dikirim!")
            break

        # Kalau gak ada tombol Next atau Submit, keluar loop
        print("Tidak menemukan tombol Next atau Submit, selesai.")
        break


if __name__ == "__main__":
    form_url = "https://docs.google.com/forms/d/e/xxxxxxxxxx/viewform"  # Ganti dengan URL form kamu

    driver = webdriver.Chrome()
    driver.get(form_url)
    time.sleep(5)  # Tunggu form load

    try:
        fill_all_sections()
    finally:
        print("Selesai, browser akan ditutup.")
        driver.quit()
